### ISSUE TITLE
run Tonemap.hlsl Shader in AviSynth

### ISSUE THREAD

**Issue by ABDOELSHEMY** [mysteryx93/AviSynthShader#17]
hi @mysteryx93 
thank you for your great work, i want to run Tonemap.hlsl Shader in AviSynth, but unfortunately i did not get it work right.
so, could you please explain how to get it work with this Shader.
thanks.

**Comment by mysteryx93** [comment]
First of all, what pixel shader version is it using? If I remember correctly, it works with PS_3_0 but not PS_4_0.

Then I use a script file like this to compile HLSL files.
https://github.com/mysteryx93/AviSynthShader/blob/master/Src/Shaders/Src/CompileHLSL.bat

**Comment by ABDOELSHEMY** [comment]
yes, you are right, it works with PS_3_0
thank you very much for your quick reply.
