### ISSUE TITLE
vapoursynth support

### ISSUE THREAD

**Issue by amayra** [mysteryx93/AviSynthShader#18]
there any hope to see AviSynthShader with vapoursynth support ?

**Comment by mysteryx93** [comment]
If I want to switch over to VapourSynth, I'll have to...

**Comment by Revan654** [comment]
I know I'm a little late to the party on this post. But did you try to load the dll with Load.avs function to see if it loads?

Some avs files will load without any issue others will not.

I would love to see some of filters created by the dev ported over to VS. Specially the FrameRateConverter.

**Comment by amayra** [comment]
> If I want to switch over to VapourSynth, I'll have to...

did you switch?

I see you included vapoursynth in multiple projects

**Comment by mysteryx93** [comment]
I'm now on Linux though; AvisynthShader has no hope of cross-platform support due to working with DX9.

However, I've seen another VapourSynth project that was doing similar, don't remember the name.

**Comment by mysteryx93** [comment]
If I remember, that VapourSynth plugin was working with MPV filters; and MPV itself is cross-platform.

**Comment by amayra** [comment]
> If I remember, that VapourSynth plugin was working with MPV filters; and MPV itself is cross-platform.

but i can't encode the video with mpv

**Comment by mysteryx93** [comment]
Found it, `vs-placebo`. Look at that one.
https://github.com/Lypheo/vs-placebo

> Runs a GLSL shader in [mpv syntax](https://mpv.io/manual/master/#options-glsl-shader).
