### ISSUE TITLE
Platform Return Code

### ISSUE THREAD

**Issue by Revan654** [mysteryx93/AviSynthShader#19]
> Cannot load file 'Shader.dll'. Platform returned code 126:
> The specified module could not be found.

This is likely due to certain CPU's only having AVX2 support with no AVX support. Not sure if you have any plans to update this filter or not.

**Comment by mysteryx93** [comment]
It is saying it can't find and load Shader.DLL at all, and thus no code within it is running. If it was an issue with wrong CPU code running, it would only crash when that code runs. Either the DLL file cannot be found in the search path, or you're trying to load the x86 into x64 Avisynth or vice-versa.

You can use AvsMeter for diagnosis and it gives information about dependencies. Trying to load wrong x64 or x86 is the most common error so I believe it gives warnings when that specific case occurs.

**Comment by Revan654** [comment]
This is the Error:

Cannot load file 'C:/Program Files (x86)/AviSynth+/plugins64/Shader.dll'. Platform returned code 126:
The specified module could not be found.

Dependencies that could not be loaded:
  d3dx9_43.dll

I assume it's DirectX build just not sure from what package it's from.

**Comment by mysteryx93** [comment]
https://validedge.com/d3dx9_43-dll-missing/

**Comment by Revan654** [comment]
> 
> 
> https://validedge.com/d3dx9_43-dll-missing/

It looked like directx needed installed. For some reason I can't get nvidia drivers to install on my PC ever since the last Win10 update. Nvidia usually is the one that installs that file it seems.

Thanks for the info

**Comment by mysteryx93** [comment]
so it's a driver issue
