### ISSUE TITLE
glsl (opengl) shader support

### ISSUE THREAD

**Issue by YohoYang** [mysteryx93/AviSynthShader#20]
Is there any hope to support glsl?
glsl is becoming more and more popular now, but it is very unfortunate, avisynth could not support it.

**Comment by mysteryx93** [comment]
Avisynth is based on DirectX 9. GLSL probably works in a later version of DirectX, where the current simplified rendering method isn't supported and it would be more complex to get it working with a later DirectX.

**Comment by YohoYang** [comment]
> Avisynth is based on DirectX 9. GLSL probably works in a later version of DirectX, where the current simplified rendering method isn't supported and it would be more complex to get it working with a later DirectX.

Understand......  so as long as I use Avisynth, there is not much hope to use OpenGL. It is really a pity, maybe there should be better things to replace Avisynth.
Thanks Reply.
