### ISSUE TITLE
Problem getting this to work

### ISSUE THREAD

**Issue by tyeeman** [mysteryx93/AviSynthShader#22]
Forgive me, I have used Avisynth lots but not in this way. The syntax is a little confusing. I've tried to fix the syntax as best I can but after loading the avs file into Vdub I get this error - 

<img width="304" alt="2020-11-09_115741" src="https://user-images.githubusercontent.com/4469306/98589890-d768e200-2282-11eb-8142-296418b4790b.png">

Here is my script - 

mov = FFVideoSource("J:\video.mp4")
ConvertToShader(mov)
Shader("G:\Adaptive-sharpen - Pass one.hlsl", Output=2)
Shader("G:\Adaptive-sharpen - Pass two.hlsl", Output=1)
ExecuteShader(last, mov, Clip1Precision=1, Precision=3, OutputPrecision=1)
ConvertFromShader()

Can you see what's wrong?

**Comment by mysteryx93** [comment]
I'm not sure. Perhaps look at the current script implementations to see what's different. It might have to do with Precision. Are you using Avisynth+?

**Comment by tyeeman** [comment]
Yes, avisynth+. I posted on doom9 also just in case you missed it here but you haven't. Where would I find the current script implementations? The following is from this repo -

ConvertToShader(1)
Input
Shader("Diff1.cso", Output=2)
Shader("Diff2.cso", Output=3)
Shader("Merge.cso", Clip1=2, Clip2=3, Output=1)
ShaderExecute(last, Input, Clip1Precision=1, Precision=3, OutputPrecision=1)
ConvertFromShader(1)

I was confused on what "Input' means. I thought it would be my variable "mov"? Do I have it in the wrong order?

Update - changed my script to this - 

ConvertToShader(1)
input = FFVideoSource("J:\video.mp4")
Shader("G:\-----New After May 4 2020\Adaptive-sharpen - Pass one.hlsl", Output=2)
Shader("G:\-----New After May 4 2020\Adaptive-sharpen - Pass two.hlsl", Output=1)
ExecuteShader(last, input, Clip1Precision=1, Precision=3, OutputPrecision=1)
ConvertFromShader(1)

I now get this error - 

<img width="300" alt="2020-11-10_201035" src="https://user-images.githubusercontent.com/4469306/98764552-e8a01480-2390-11eb-87a8-af7361974488.png">

**Comment by tyeeman** [comment]
I got some help on doom9 and it loads into Vdub now and plays, but the width is 1/2 of what it should be and the image is all covered in blue.
